### Quset
- dataset desc : RecurrenceOfSurgery.md
- toy_machinlearing (git)
- refer : 전처리, 모델학습
- 업무분장(전처리, 모델학습).
- RecurrenceOfSurgery.csv 사용
- 목표변수 : 범주형, 설명변수 : 최소 6개 
- 서비스 대상과 목표 설명, 변수 선택 이유

In [1]:
import pandas as pd

In [2]:
df_ROS = pd.read_csv('../datasets/RecurrenceOfSurgery.csv')
df_ROS

,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,0,1PT,22.8,3,51.0,0.0,0,0,0,0,...,3,51.6,36.6,14.4,0,-1.01,2048.50,4,Down,0
1,1,2PT,44.9,4,26.0,0.0,0,0,0,0,...,0,40.8,7.2,17.8,0,-1.14,1753.10,4,Up,0
2,2,3PT,53.0,3,NaN,0.0,0,0,1,0,...,0,67.5,27.3,10.2,0,-1.77,1749.00,4,Down,0
3,3,4PT,54.7,4,18.0,0.0,0,1,0,0,...,0,49.2,18.7,19.9,0,-1.58,1796.20,4,Down,0
4,4,5PT,53.8,4,NaN,0.0,0,1,0,0,...,0,58.8,14.7,5.2,0,-0.79,2021.48,4,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,1889,1890PT,44.0,1,NaN,0.0,0,0,0,0,...,2,59.5,23.0,21.8,0,NaN,2652.20,5,Middle,0
1890,1890,1891PT,30.8,2,NaN,0.0,0,0,0,0,...,0,47.7,20.2,5.0,0,NaN,1795.80,4,Down,0
1891,1891,1892PT,36.7,3,NaN,0.0,0,0,0,0,...,0,44.6,15.0,17.4,1,NaN,2624.40,4,Down,0
1892,1892,1893PT,32.5,2,NaN,0.0,0,0,0,0,...,2,32.2,11.1,17.7,0,NaN,1972.50,5,Down,0
1893,1893,1894PT,49.5,2,NaN,0.0,0,0,0,0,...,0,38.9,6.8,27.8,0,NaN,1574.40,5,Middle,0

In [3]:
df_ROS.columns

Index(['Unnamed: 0', '환자ID', 'Large Lymphocyte', 'Location of herniation',
       'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수', '당뇨여부', '말초동맥질환여부', '빈혈여부',
       '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환', '암발병여부', '연령', '우울증여부', '입원기간',
       '입원일자', '종양진행여부', '직업', '체중', '퇴원일자', '헤모글로빈수치', '혈전합병증여부', '환자통증정도',
       '흡연여부', '통증기간(월)', '수술기법', '수술시간', '수술실패여부', '수술일자', '재발여부', '혈액형',
       '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도', 'Instability', 'MF + ES',
       'Modic change', 'PI', 'PT', 'Seg Angle(raw)', 'Vaccum disc', '골밀도',
       '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

####  목표변수
- 목표변수 : 스테로이드 치료
- 설명변수 : '고혈압여부','흡연여부','입원기간','통증기간(월)','헤모글로빈수치','연령'
- 서비스대상 : 환자

In [6]:
df_ROS_ex = df_ROS[['스테로이드치료','고혈압여부','흡연여부','입원기간','통증기간(월)','헤모글로빈수치','연령']]
df_ROS_ex

      스테로이드치료  고혈압여부  흡연여부  입원기간  통증기간(월)  헤모글로빈수치  연령
0           1      0     0     2      1.0    13.66  66
1           1      0     0     1      1.0    13.73  47
2           1      0     0     1      1.0    15.34  39
3           0      1     0     1      2.0    15.38  40
4           1      1     0     2      1.0    13.08  42
...       ...    ...   ...   ...      ...      ...  ..
1889        1      0     0     2     12.0    13.60  59
1890        1      0     0     4      6.0    13.00  42
1891        1      0     0     3      1.0    14.40  61
1892        1      0     0     4     24.0    15.00  29
1893        1      0     0     2      6.0    13.20  30

[1894 rows x 7 columns]

#### Pre-Processing (전처리)

In [5]:
df_ROS_ex.isnull().sum()

스테로이드치료    0
고혈압여부      0
흡연여부       0
입원기간       0
통증기간(월)    4
헤모글로빈수치    1
연령         0
dtype: int64

In [15]:
df_ROS_ex_d = df_ROS_ex.dropna()   # 결측치가 있는 행 삭제

#### Encoding
- 범주형 변수를 변환 할게 없어서 생략!

In [34]:
from sklearn.preprocessing import OneHotEncoder